name: Django CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: django_test
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - uses: actions/checkout@v3  # Updated to v3
     
      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: 3.8
          cache: 'pip' 
          cache-dependency-path: '**/requirements.txt'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install django djangorestframework
          pip install -r requirements.txt

      - name: Run tests
        env:
          DATABASE_URL: postgres://user:password@localhost:5432/django_test
        run: |
          python manage.py test

