name: Django CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: django_test
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django djangorestframework
        pip install -r requirements.txt
    - name: Run tests
      env:
        DATABASE_URL: postgres://user:password@localhost:5432/django_test
      run: |
        python manage.py test
